<a href="https://colab.research.google.com/github/b-bhupendra/Learning-ML-/blob/main/Lecture_2_Basics_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
P = np.array([[1,7],[2,1],[3,2]])
print(P)

[[1 7]
 [2 1]
 [3 2]]


In [6]:
Q = np.array([[1,1],[1,-1],[1,0]])
print(Q)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [8]:
C1 = np.add(P,Q)
C1

array([[2, 8],
       [3, 0],
       [4, 2]])

In [9]:
C2 = np.subtract(P,Q)
C2

array([[0, 6],
       [1, 2],
       [2, 2]])

In [11]:
R = np.array([[1,3,1],[1,0,1]])
R

array([[1, 3, 1],
       [1, 0, 1]])

In [13]:
C2 = np.dot(P,R)
C2

array([[8, 3, 8],
       [3, 6, 3],
       [5, 9, 5]])

In [15]:
det = np.linalg.det(C2)
det

0.0

In [16]:
inverse = np.linalg.inv(C2)
inverse

LinAlgError: Singular matrix

In [18]:
M = np.array([[1,-1],[2,3]])
print(M)
print(np.linalg.inv(M))

[[ 1 -1]
 [ 2  3]]
[[ 0.6  0.2]
 [-0.4  0.2]]
