<a href="https://colab.research.google.com/github/b-bhupendra/Learning-ML-/blob/main/Lecture_1_Vectors_in_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
v = np.array([1,-1,2])
w = np.array([2,5,2])

print(v + w)

[3 4 4]


In [3]:
print(v - w)

[-1 -6  0]


In [4]:
# scalar Mult:
print(3*v)

[ 3 -3  6]


In [5]:
# Magnitude / Norm / Lenght of the vector
print(np.linalg.norm(v))

2.449489742783178


In [7]:
s = np.dot(v, w)

print(s)

1
