# Problem Statement: **Welcome to AI Town!**

### You’ve been hired as an AI engineer in **AI Town**, a futuristic city powered by artificial intelligence. Your job is to use PyTorch to solve foundational challenges that AI Town faces. Each task requires you to demonstrate your expertise with PyTorch basics.



---



Imports and CUDA

In [17]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

import torch as t

# Check if CUDA (GPU) is available
device = t.device('cuda' if t.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


Looking in indexes: https://download.pytorch.org/whl/cu121
Using device: cpu




---



**Task1: Inventory Management**

AI Town’s warehouse uses sensors to record the inventory of 5 items every day. Each day’s data is represented as a list of integers (number of units).

In [18]:
#1 Create a PyTorch Tensor from the following inventory data
inventory = [[12, 15, 10, 0, 5], #1
             [10, 8, 7, 5, 4], #2
             [20, 10, 15, 5, 2]] #3
t.Tensor(inventory)

tensor([[12., 15., 10.,  0.,  5.],
        [10.,  8.,  7.,  5.,  4.],
        [20., 10., 15.,  5.,  2.]])

In [20]:
#2 Find the total inventory for each item across all days
t.sum(t.Tensor(inventory), dim=0)

tensor([42., 33., 32., 10., 11.])

In [6]:
#3 Find the average inventory per day
t.mean(t.Tensor(inventory), dim=1)

tensor([ 8.4000,  6.8000, 10.4000])



---



**Task2: Monitoring Vehicle Flow**

AI Town uses a sensor to monitor the number of vehicles passing through two main roads every hour. The data for one day (24 hours) is represented as two
1×24 tensors.

In [37]:
#1 Simulate this data using PyTorch's Random Functions
t.manual_seed(42)
def one_day():
  ls = [[t.random.seed() for _ in range(24) ] ,[t.random.seed() for _ in range(24)]]
  return t.Tensor(ls)

one_day()

tensor([[1.8179e+19, 1.5945e+18, 2.1887e+18, 1.1171e+19, 1.7735e+19, 1.0919e+19,
         6.7307e+18, 2.6797e+18, 5.2710e+18, 9.5273e+18, 6.5210e+18, 1.1562e+17,
         7.6845e+18, 1.2524e+19, 7.5702e+18, 7.0048e+18, 6.1533e+18, 1.1361e+19,
         1.5475e+19, 1.4496e+19, 4.7489e+18, 1.5456e+19, 1.3871e+19, 6.3877e+18],
        [8.5207e+18, 1.7104e+19, 1.7488e+19, 7.3734e+18, 3.3477e+18, 2.2844e+18,
         1.6870e+19, 6.6480e+18, 8.9926e+18, 6.3174e+17, 1.2017e+19, 1.2724e+18,
         1.6832e+19, 1.0906e+19, 6.5781e+18, 9.7954e+18, 2.8565e+18, 1.3836e+19,
         1.5487e+19, 1.5571e+19, 7.5060e+18, 9.1665e+18, 1.5543e+19, 1.3227e+19]])

In [42]:
#2 Write the function to calculate the total vehicle flow for each road across the entire day
def total_flow(data):
  return [a.item() for a in t.sum(data, dim=1)]

total_flow(one_day())

[2.121709644089582e+20, 2.183513632491522e+20]

In [43]:
#3 Write the function to calculate the total vehicle flow for each hour across both roads
def total_flow(data):
  return [a.item() for a in t.sum(data, dim=0)]
total_flow(one_day())

[3.0988758862541095e+19,
 1.0284110486588883e+19,
 1.271851719141517e+19,
 1.8654151549126705e+19,
 1.8081939309753008e+19,
 9.152914232235262e+18,
 1.3360902461896786e+19,
 3.289734832063932e+19,
 2.370288464350203e+19,
 2.6578707883485037e+19,
 2.31868618463542e+19,
 4.957187756246696e+18,
 2.6088811681636418e+19,
 1.2021441113056346e+19,
 1.25384820579715e+19,
 1.3363382960129049e+19,
 2.178744522796276e+19,
 2.757846082127292e+19,
 1.8370598495439553e+19,
 1.5299715295619318e+19,
 3.1043980734534517e+19,
 7.104282177130463e+18,
 1.111243856649021e+19,
 5.809371939935879e+18]



---



**Task3: Fitness Matrix**

The AI Gym tracks members’ fitness scores using a 3×3 matrix for *strength*, *stamina*, and f*lexibility*. Each row represents a different member, and each column represents a specific metric.

In [64]:
#1 Create a 3*3 tensor matrix and multiply the scores of each member by a weight factor: [0.8, 1.2, 1.5]
tensor1 = torch.randint(0, 10, (3, 3))
tensor1 * torch.Tensor([0.8, 1.2, 1.5])

tensor([[ 0.8000,  0.0000,  4.5000],
        [ 4.8000,  3.6000, 10.5000],
        [ 2.4000,  4.8000, 13.5000]])

In [66]:
#2 Find the row-wise and column-wise maximum scores
display(tensor1)
print(t.max(tensor1, dim=0))
print(t.max(tensor1, dim=1))

tensor([[1, 0, 3],
        [6, 3, 7],
        [3, 4, 9]])

torch.return_types.max(
values=tensor([6, 4, 9]),
indices=tensor([1, 2, 2]))
torch.return_types.max(
values=tensor([3, 7, 9]),
indices=tensor([2, 2, 2]))


In [68]:
#3 Transpose the fitness matrix and interpret it's new structure (shape)
tensor1.T.shape

torch.Size([3, 3])



---



**Task4: Chain Rule in Action**

AI Lab is running experiments to understand the effect of temperature (
x) on a chemical reaction rate (y). The relationship is given as:
$y = 2x^3 + 5x^2 - 3x + 7$



In [74]:
#1 Use PyTorch to compute 'y' for x = 1
x = t.tensor(1.0, requires_grad=True) # value of x in f(x) {y} is 1 .
y = 2 * x**3 + 5 * x**2 - 3 * x + 7

In [75]:
#2 Calculate dy/dx(gradient) using PyTorch's autograd
y.backward()
print(x.grad)

tensor(13.)




---



**Task5: Camera Calibration**

AI Town’s surveillance cameras need to align their focus. You are given the following matrices for two cameras’ focus adjustments:

In [91]:


camera1 = t.tensor([[1., 2.],
                    [3., 4.]])
camera2 =  t.tensor([[5., 6.],
                      [7., 8.]])

In [92]:
#1 Perform an element-wise multiplication of matrices ( Hadamard Product)
camera1*camera2

tensor([[ 5., 12.],
        [21., 32.]])

In [93]:
#2 Compute Dot Product of the two matrices
camera1 @ (camera2)


tensor(-2.)

In [95]:
#3 Compute the Determinant of each matrix
camera1.det(),camera2.det()

(tensor(-2.), tensor(-2.0000))



---



**Task6: Neural Network Foundations**

Our AI University uses simplified single neuron model (perceptron):
$$y = wx + b$$

In [109]:
#1 Create tensors for w  = 2, b = 1, x = [1, 2, 3, 4]
w  = t.tensor(2)
b = t.tensor(1)
x_s = t.tensor([1,2,3,4])

In [112]:
#1 Use PyTorch to compute 'y' for x = 1
y = w * x_s + b

tensor([3, 5, 7, 9])

In [113]:
#2 Compute tensors for y
y

tensor([3, 5, 7, 9])



---

